# Generated by Django 3.2.12 on 2024-12-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件'),
        ),
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_fullpage',
            field=models.BooleanField(default=False, verbose_name='是否全屏'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='路由'),
        ),
        migrations.AddField(
            model_name='permission',
            name='route_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='路由名称'),
        ),
    ]
