# Generated by Django 4.2.19 on 2025-07-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_dept_create_by_alter_dept_update_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='男', max_length=10, verbose_name='性别'),
        ),
    ]
