# Generated by Django 4.2.27 on 2026-01-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_dept_create_by_alter_dept_third_info_and_more'),
        ('system', '0007_alter_dept_create_by_alter_dept_update_by_and_more'),
    ]

    operations = [
    ]
