# Generated by Django 4.2.19 on 2025-03-23 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0007_alter_dept_create_by_alter_dept_update_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atask',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('year', models.PositiveIntegerField(verbose_name='审计年度')),
                ('state', models.PositiveSmallIntegerField(choices=[(10, '待开始'), (20, '进行中'), (30, '已完成')], default=10, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='得分')),
            ],
            options={
                'verbose_name': '审计任务',
                'verbose_name_plural': '审计任务',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标准名称')),
                ('to_type', models.PositiveSmallIntegerField(choices=[(10, '矿山'), (20, '水泥'), (30, '商混')], default=10, verbose_name='适用类型')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='总分')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
            ],
            options={
                'verbose_name': '审计标准',
                'verbose_name_plural': '审计标准',
            },
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('number', models.CharField(max_length=100, verbose_name='条款号')),
                ('level', models.PositiveSmallIntegerField(choices=[(10, '一级'), (20, '二级'), (30, '三级')], default=10, verbose_name='条款等级')),
                ('risk_level', models.PositiveSmallIntegerField(choices=[(10, '低风险'), (20, '中风险'), (30, '高风险'), (40, '重大风险')], default=10, verbose_name='风险等级')),
                ('content', models.TextField(verbose_name='条款内容')),
                ('method', models.TextField(verbose_name='考评办法')),
                ('full_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='满分分值')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.standarditem', verbose_name='上级条款')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.standard', verbose_name='关联审计标准')),
            ],
            options={
                'verbose_name': '审计标准条款',
                'verbose_name_plural': '审计标准条款',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('level', models.PositiveSmallIntegerField(choices=[(10, '集团'), (20, '区域'), (30, '公司')], verbose_name='公司级别')),
                ('types', models.JSONField(blank=True, default=list, null=True, verbose_name='类型')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.company', verbose_name='上级')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
            ],
            options={
                'verbose_name': '受审计单位',
                'verbose_name_plural': '受审计单位',
            },
        ),
        migrations.CreateModel(
            name='AtaskTeam',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('duty_type', models.PositiveSmallIntegerField(choices=[(10, '组长'), (20, '组员')], verbose_name='职责类型')),
                ('atask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_atask', to='audit.atask', verbose_name='关联审计任务')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '审计任务组',
                'verbose_name_plural': '审计任务组',
            },
        ),
        migrations.CreateModel(
            name='AtaskItem',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('is_suit', models.BooleanField(default=True, verbose_name='是否适用')),
                ('checked', models.BooleanField(default=False, verbose_name='是否已检查')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('kill_score', models.PositiveSmallIntegerField(default=0, verbose_name='扣分')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='得分')),
                ('atask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.atask', verbose_name='关联审计任务')),
                ('check_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='检查人')),
                ('standarditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.standarditem', verbose_name='关联审计标准条款')),
            ],
            options={
                'verbose_name': '审计条款',
                'verbose_name_plural': '审计条款',
            },
        ),
        migrations.CreateModel(
            name='AtaskIssue',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=20, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('ataskitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.ataskitem', verbose_name='关联审计条款')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('photos', models.ManyToManyField(blank=True, to='system.file', verbose_name='问题照片')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
            ],
            options={
                'verbose_name': '审计问题',
                'verbose_name_plural': '审计问题',
            },
        ),
        migrations.AddField(
            model_name='atask',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.company', verbose_name='审计对象'),
        ),
        migrations.AddField(
            model_name='atask',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='atask',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.standard', verbose_name='审计标准'),
        ),
        migrations.AddField(
            model_name='atask',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人'),
        ),
    ]
