# Generated by Django 4.2.19 on 2025-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='cate',
            field=models.PositiveSmallIntegerField(choices=[(10, '基础部分'), (20, '现场部分')], default=10, verbose_name='大类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='条款内容'),
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '一级'), (20, '二级'), (30, '三级')], default=10, null=True, verbose_name='条款等级'),
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='method',
            field=models.TextField(blank=True, null=True, verbose_name='考评办法'),
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='risk_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '低风险'), (20, '中风险'), (30, '高风险'), (40, '重大风险')], default=10, null=True, verbose_name='风险等级'),
        ),
    ]
