# Generated by Django 4.2.19 on 2025-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_standarditem_cate_alter_standarditem_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarditem',
            name='risk_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '低风险'), (20, '中风险'), (30, '高风险'), (40, '重大风险')], null=True, verbose_name='风险等级'),
        ),
    ]
