# Generated by Django 4.2.19 on 2025-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_standarditem_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='is_concern',
            field=models.BooleanField(default=False, verbose_name='是否最小扣分项'),
        ),
    ]
