# Generated by Django 4.2.19 on 2025-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_standarditem_is_concern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataskitem',
            name='checked',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否已检查'),
        ),
        migrations.AlterField(
            model_name='ataskitem',
            name='is_suit',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否适用'),
        ),
        migrations.AlterField(
            model_name='ataskitem',
            name='kill_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='扣分'),
        ),
    ]
