# Generated by Django 4.2.19 on 2025-05-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_ataskitem_checked_alter_ataskitem_is_suit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarditem',
            name='cate',
        ),
    ]
