# Generated by Django 4.2.19 on 2025-05-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_remove_standarditem_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ataskissue',
            name='ataskitem',
        ),
        migrations.AddField(
            model_name='ataskissue',
            name='atask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.atask', verbose_name='关联审计任务'),
        ),
        migrations.AddField(
            model_name='ataskissue',
            name='standarditem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.standarditem', verbose_name='关联审计标准条款'),
        ),
        migrations.AlterField(
            model_name='ataskissue',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='问题内容'),
        ),
    ]
