# Generated by Django 4.2.19 on 2025-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_remove_ataskissue_ataskitem_ataskissue_atask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='number_sort',
            field=models.CharField(blank=True, null=True, verbose_name='排序号'),
        ),
    ]
