# Generated by Django 4.2.19 on 2025-06-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataskissue',
            name='kill_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='扣分'),
        ),
    ]
