# Generated by Django 4.2.19 on 2025-06-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_ataskissue_kill_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataskissue',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='问题编号'),
        ),
    ]
