# Generated by Django 4.2.19 on 2025-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_ataskissue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话'),
        ),
    ]
