# Generated by Django 4.2.19 on 2025-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_company_address_company_contact_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='atask',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='atask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
    ]
