# Generated by Django 4.2.19 on 2025-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_atask_end_date_atask_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='atask',
            name='notify_content',
            field=models.TextField(blank=True, null=True, verbose_name='通知内容'),
        ),
    ]
