# Generated by Django 4.2.19 on 2025-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_atask_notify_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='audit_scope',
            field=models.TextField(blank=True, null=True, verbose_name='审计范围'),
        ),
    ]
