# Generated by Django 4.2.19 on 2025-07-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_company_audit_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataskissue',
            name='risk_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '低风险'), (20, '中风险'), (30, '高风险'), (40, '重大风险')], null=True, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='ataskissue',
            name='standarditem_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_standarditem_1', to='audit.standarditem', verbose_name='关联一级条款'),
        ),
        migrations.AddField(
            model_name='ataskissue',
            name='standarditem_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_standarditem_2', to='audit.standarditem', verbose_name='关联二级条款'),
        ),
        migrations.AlterField(
            model_name='ataskissue',
            name='standarditem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_standarditem', to='audit.standarditem', verbose_name='关联审计标准条款'),
        ),
    ]
