# Generated by Django 4.2.19 on 2025-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_ataskproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='atask',
            name='full_score',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='满分'),
        ),
    ]
