# Generated by Django 3.2.12 on 2025-09-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0002_alter_state_filter_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='view_path',
            field=models.TextField(blank=True, null=True, verbose_name='前端自定义页面路径'),
        ),
    ]
