# Generated by Django 3.2.12 on 2025-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0003_workflow_view_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分类'),
        ),
    ]
