# Generated by Django 3.2.12 on 2025-12-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0005_workflow_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='content_template',
            field=models.TextField(blank=True, default='标题:{title}, 创建时间:{create_time}', help_text='工单字段的值可以作为参数写到模板中，格式如：标题:{title}, 创建时间:{create_time}', null=True, verbose_name='内容模板'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='title_template',
            field=models.TextField(blank=True, default='{title}', help_text='工单字段的值可以作为参数写到模板中，格式如：你有一个待办工单:{title}', null=True, verbose_name='标题模板'),
        ),
    ]
